### ISSUE TITLE
[doc] Improved project description

### ISSUE THREAD

**Issue by matgessel** [matan1008/objc-types-decoder#3]
I found this project when searching on PyPI for autocompletion / type hinting for PyObjC. Initially, I thought this project might be a mypy stub generator for PyObjC.

Suggested additions to documentation:

----

A type decoder for Objective-C types. 

Translates the hard-to-read Objective-C type notation into [TODO: a more readable form? Objective-C code?]

TODO: Describe project motivation:

- ex 1 — Figuring out how to call undocumented Objective-C code
- ex 2 — To ensure correct translation of arguments, it is sometimes necessary to explicitly specify the type encoding for an Objective-C selector
- ex 3 — Implementing Objective-C callbacks in Python using PyObjC's `objc.selector`

More information on Objective-C type encodings here:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html#//apple_ref/doc/uid/TP40008048-CH100

And here:
https://jimmatthews.wordpress.com/2007/07/12/objcselector-and-objcsignature/

**Comment by matan1008** [comment]
Thanks for the review! 
I added some more documentation, is it more clear now?

**Comment by matgessel** [comment]
Looks good to me.
